# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hw3' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hw3

end
pod 'AFNetworking'
pod 'Masonry' 